spring:
  application:
    name: ZBprovider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yaomanagement?serverTimezone=UTC
    username: root
    password: root
server:
  port: 8003

mybatis:
  type-aliases-package: com.lilongjian.domain
  mapper-locations: classpath:mappers/*.xml

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZeon: http://localhost:8761/eureka

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
